### ISSUE TITLE
Question about the Lock and Unlock methods

### ISSUE THREAD

**Issue by Jonathan-79** [ss098/certmagic-s3#12]
Hello,

It seems like in mid 2021 you guys rewrote the package to remove the Redis dependency, is that correct? 
I'm reading the current code and it appears that the implementation for the Lock and Unlock method that previously used Redis are now empty:

```
func (s3 S3) Lock(ctx context.Context, key string) error {
	return nil
}

func (s3 S3) Unlock(ctx context.Context, key string) error {
	return nil
}
```

I was wondering if the lock is not needed anymore in the current implementation and if the current implementation supports multiple caddy instances running in parallel accessing the same s3 storage space

**Comment by ss098** [comment]
I did rewrite to remove the Redis lock, and this is because I had some issues with my implementation of the Redis lock.

But that doesn't mean it doesn't need locks, the current implementation just ignores it and distributed scenarios may still have some issues.
