### ISSUE TITLE
Not using github.com/aws/aws-sdk-go/service/s3 ?

### ISSUE THREAD

**Issue by JohnPreston** [ss098/certmagic-s3#4]
Hello.
Just ran into this module. Just wondering why not using the AWS GO SDK (github.com/aws/aws-sdk-go/service/s3) ?
Among other things, it will allow to pick the AWS Credentials directly using the SDK credentials chain.
Thanks :)

**Comment by ss098** [comment]
Hi,

because of the larger package size of the AWS SDK, I wanted this module to be kept simple, so I chose the MinIO SDK.
