### ISSUE TITLE
Problem building against 2.5.0-rc1 / Master

### ISSUE THREAD

**Issue by hevisko** [ss098/certmagic-s3#5]
Using `xcaddy build master --with github.com/ss098/certmagic-s3` I get the error below (seems to be also happening for redistls storage module). Building against 2.4.6 everything seems fine.

```
2022/04/18 10:19:02 [INFO] exec (timeout=0s): /usr/bin/go get -d -v
2022/04/18 10:19:05 [INFO] Build environment ready
2022/04/18 10:19:05 [INFO] Building Caddy
2022/04/18 10:19:05 [INFO] exec (timeout=0s): /usr/bin/go mod tidy
2022/04/18 10:19:05 [INFO] exec (timeout=0s): /usr/bin/go build -o /root/caddy/caddy -ldflags -w -s -trimpath
# github.com/ss098/certmagic-s3
/root/go/pkg/mod/github.com/ss098/certmagic-s3@v0.0.0-20211201134104-efad3a48d4ed/s3.go:127:2: cannot use s3 (type S3) as type certmagic.Storage in return argument:
        S3 does not implement certmagic.Storage (wrong type for Delete method)
                have Delete(string) error
                want Delete(context.Context, string) error
2022/04/18 10:19:09 [INFO] Cleaning up temporary folder: /tmp/buildenv_2022-04-18-1018.2928695872
2022/04/18 10:19:09 [FATAL] exit status 2
root@apt-cacher:~/caddy# go version
go version go1.17.8 linux/amd64
```

**Comment by Kendysond** [comment]
This is so odd because I setup caddy 4 days ago and everything worked perfectly, however, today I wanted to make some update and my builds started failing. 

Forcing v2.4.6 didn't seem to work for me but via my logs I did notice that the build kept upgrading caddy to 2.5.0. On my xcaddy `--with` options, I had `caddy-tlsredis` and `certmagic-s3`, and I noticed `caddy-tlsredis` seems to be what's responsible for it, so I removed it (I wasn't using redis anymore) and everything seems to work fine now. 

My command looks like this now:

```
FROM caddy:2.4.6-builder-alpine AS builder

RUN xcaddy build v2.4.6 \
    --with github.com/ss098/certmagic-s3

FROM caddy:2.4.6-alpine

....
```

**Comment by ss098** [comment]
This issue may be resolved by Pull Request #6.

**Comment by Kendysond** [comment]
Hi @ss098 , this is so weird because my setup that was working just a few hours ago isn't working anymore. lol. Even with this new PR

**Comment by ss098** [comment]
I try to solve this problem, the storage interface is fine, but Caddy doesn't work.

**Comment by XanderBoedt** [comment]
Probably a stupid question but is there a way to get the certmagic-s3 version back from before Pull Request #6 ?
With this we can have a temporary workaround by locking caddy on version 2.4.6.
Because the changes in #6 makes the module incompatible with versions prior 2.5.0

**Comment by ss098** [comment]
> 

—with github.com/ss098/certmagic-s3@ efad3a48d4edfbe2fee64e9c4d04195603822b07

**Comment by XanderBoedt** [comment]
> @ [efad3a4](https://github.com/ss098/certmagic-s3/commit/efad3a48d4edfbe2fee64e9c4d04195603822b07)

Thank you, works perfect!
