### ISSUE TITLE
Storage logger leaks sensitive values

### ISSUE THREAD

**Issue by gojihotsauce** [ss098/certmagic-s3#8]
Please reference issue: https://github.com/caddyserver/caddy/issues/4780

The plugin should implement the [`Stringer` interface](https://pkg.go.dev/fmt#Stringer), which would let it control how the struct is serialized as a string with `%v`.

Caddy needs to convert the struct to a string to use as an ID as a unique key for the storage plugin. The plugin can control what that ID is by being a `Stringer`.

Admittedly, this wasn't well documented, so that's partly our-bad.

Either way, we can't recommend using the S3 plugin, because it doesn't properly implement the locking mechanisms required by the storage interface.

_Originally posted by @francislavoie in https://github.com/caddyserver/caddy/issues/4780#issuecomment-1122876929_

**Comment by ss098** [comment]
Hi, I will try to solve this problem recently.

**Comment by arbourd** [comment]
Any movement on this @ss098?

**Comment by ss098** [comment]
This issue has been resolved by commit [a1c27a31f74fa5f80c8530e9ee010cfab292f5d9](https://github.com/ss098/certmagic-s3/commit/a1c27a31f74fa5f80c8530e9ee010cfab292f5d9).
