### ISSUE TITLE
[Request] Publish plugin to Caddy download page

### ISSUE THREAD

**Issue by nsinisterra** [ss098/certmagic-s3#9]
Hi there!

ss098, may I ask you to publish your package in https://caddyserver.com/download? That would allow us to download it from the package manager.

I think that do that is really easy, based on the community forum you should:

1. Create an account in https://caddyserver.com/account/create
2. Send your package using https://caddyserver.com/account/

Thats it and will be really helpful!

Thanks so much for your work!

**Comment by ss098** [comment]
Hi,

this package has been published before, I just logged into my account and found the available option unchecked, I checked it and republished it.
